App_login/urls.py
from django.urls import path
from . import views

app_name = 'App_login'

urlpatterns = [
    path('retistion/',views.retistion, name='retistion'),
    path('login/',views.login_user, name='login'),
    # path('profile/',views.change_pro_pic, name='profile_info'),
    path('profile/',views.ProfilePicAdd, name='profile_info'),
    path('change_pro_pic/',views.change_pro_pic, name='change_pro_pic'),

    path('bag_img_profile/',views.bag_img_profile, name='bag_img_profile'),
    path('change_pro_pic_bg/',views.change_pro_pic_bg, name='change_pro_pic_bg'),
    
    path('password_change/',views.password_change, name='password_change'),

    path('logout/',views.logout_user, name='logout'),
    path('ChangeProInfo/',views.ChangeProInfo, name='ChangeProInfo'),
]

App_post/urls.py
from django.urls import path
from . import views

app_name= 'App_post'

urlpatterns = [
    path('', views.home, name='home'),
    path('MyBlogs', views.MyBlogs.as_view(), name='MyBlogs'),
    path('EditBlog/<pk>/', views.EditBlog.as_view(), name='EditBlog'),
    path('Create_blog/', views.Create_blog.as_view(), name='Create_blog'),
    # path(r'^BlogDitlis/(?P<slug>[\w-]+)/$',views.blog_deitels,name='blog_detiels'),
    path('BlogDitlis/<slug>/',views.blog_deitels,name='blog_detiels'),
    # path(r'^BlogDitlis1/(?P<slug>[\w-]+)/$',views.BlogDetitel,name='BlogDetitel1'),
    path('BlogDitlis1/<slug>/',views.BlogDetitel,name='BlogDetitel1'),
    path('Like/<pk>/',views.UserLike, name='like'),
    path('unLike/<pk>/',views.UserUnlike, name='Unlike'),
    path('orprofile/<username>/',views.OrderUserProfile, name='or_profile'),

]

New_Blog_Project_Mester/urls.py
from django.views.static import serve
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounds/', include('App_login.urls')),
    path('post/', include('App_post.urls')),
    path('',views.home, name='home'),
]

handler404 = views.handler404
handler400 = views.handler404

urlpatterns +=  staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_login/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile (models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_images')

class UserProfileBackround (models.Model):
    user = models.OneToOneField(User, related_name='user_profile_bg', on_delete=models.CASCADE)
    profile_pic_bg = models.ImageField(upload_to='profile__bg_images')

App_login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UserChangeForm,PasswordChangeForm
from django.contrib.auth.models import User
from django.db.models.fields.files import ImageField
from django.forms import fields
from django.forms.widgets import Widget
from .models import UserProfile,UserProfileBackround


class registion (UserCreationForm):
    email = forms.EmailField(required=True, label='', widget=forms.TextInput(attrs={'placeholder':'Email'}))
    username = forms.CharField(required=True, label='', widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password1 = forms.CharField(required=True, label='', widget=forms.TextInput(attrs={'placeholder':' Password', 'type':'password'}))
    password2 = forms.CharField(required=True, label='', widget=forms.TextInput(attrs={'placeholder':' Password Confarmition', 'type':'password'}))
    class Meta:
        model = User
        fields =('email','username','password1','password2',)

class User_login(AuthenticationForm):
    username = forms.CharField(required=True, label='', widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password = forms.CharField(required=True, label='', widget=forms.TextInput(attrs={'placeholder':' Password', 'type':'password'}))
    class Meta:
        fields = ('username','password')

class UserChangeProInfo(UserChangeForm):
    email = forms.EmailField(required=False, label='', widget=forms.TextInput(attrs={'placeholder':' Email'}))
    username = forms.CharField(required=True, label='', widget=forms.TextInput(attrs={'placeholder':' Username'}))
    first_name = forms.CharField(required=False, label='', widget=forms.TextInput(attrs={'placeholder':'first_name'}))
    last_name = forms.CharField(required=False, label='', widget=forms.TextInput(attrs={'placeholder':' last_name'}))
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email')


class add_profilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_pic',)

class BackgroundImage(forms.ModelForm):
    class Meta:
        model = UserProfileBackround
        fields = ('profile_pic_bg',)


# class PasswordChUser(PasswordChangeForm):
#     password = forms.CharField(required=True,label='',widget=forms.PasswordInput(attrs={'placeholder':' Carrent Password','type':'password'}))
#     password1 = forms.CharField(required=True,label='',widget=forms.PasswordInput(attrs={'placeholder':' New Password','type':'password'}))
#     password2 = forms.CharField(required=True,label='',widget=forms.PasswordInput(attrs={'placeholder':' Conform Password','type':'password'}))
#     class Meta:
#         fields = ('password','password1','password2',)

App_login/views.py
import django
from django.contrib.messages.api import success
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from .forms import registion,User_login,UserChangeProInfo,add_profilePic,BackgroundImage
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from .models import UserProfile

# Create your views here.


def retistion(request):
    form = registion()
    if request.method == 'POST':
        form = registion(data = request.POST)
        if form.is_valid():
           form.save()
           messages.success(request,'You have Successfully Sign up here ! Please @Login')
           return HttpResponseRedirect(reverse('App_login:login'))
    return render(request,'App_login/registion.html',context={'form':form})

def login_user(request):
    form = User_login()
    if request.method == 'POST':
        form = User_login(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data .get('password')
            user = authenticate(username=username,password=password)
            if user is not None:
                login (request,user)
                messages.success(request,'You have successfully Login')
                return HttpResponseRedirect(reverse('home'))
    return render(request,'App_login/login.html', context={'form':form })

@login_required()
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_login:profile_info'))

@login_required()
def ChangeProInfo(request):
    form = UserChangeProInfo(instance=request.user)
    if request.method == 'POST':
        form = UserChangeProInfo(request.POST,instance = request.user)
        if form.is_valid():
            form.save()
            messages.success(request,'Your information successfully Update !')
            return HttpResponseRedirect(reverse('App_login:profile_info'))
    return render(request,'App_login/ch_pro_info.html',context={'form':form})

@login_required()
def password_change(request):
    form = PasswordChangeForm(request.user)
    if request.method == 'POST':
        form = PasswordChangeForm(request.user,data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Your Password Successfully Change !')
            return HttpResponseRedirect(reverse('App_login:profile_info'))
    return render(request,'App_login/password_ch.html',context={'form':form})


# Profile Image
@login_required()
def ProfilePicAdd(request):
    form = add_profilePic()
    if request.method =='POST':
        form = add_profilePic(request.POST,request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            messages.success(request,'Your Profile Picture Successfully Add ')
            return HttpResponseRedirect(reverse('App_login:profile_info'))
    return render(request,'App_login/profile.html',context={'form':form})

@login_required()
def change_pro_pic(request):
    form = add_profilePic(instance=request.user.user_profile)
    if request.method == 'POST':
        form = add_profilePic(request.POST,request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            messages.success(request,'Your Profile Picture Successfully Add ')
            return HttpResponseRedirect(reverse('App_login:profile_info'))
    return render(request,'App_login/profile_pic_ch.html',context={'form':form})


# Profile BackgroundImage
@login_required()
def bag_img_profile(request):
    form = BackgroundImage()
    if request.method =='POST':
        form = BackgroundImage(request.POST,request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            messages.success(request,'Your Profile Picture Successfully Add ')
            return HttpResponseRedirect(reverse('App_login:profile_info'))
    return render(request,'App_login/background.html',context={'form':form})

@login_required()
def change_pro_pic_bg(request):
    form = BackgroundImage(instance=request.user.user_profile_bg)
    if request.method == 'POST':
        form = BackgroundImage(request.POST,request.FILES, instance=request.user.user_profile_bg)
        if form.is_valid():
            form.save()
            messages.success(request,'Your Profile Picture Successfully Add ')
            return HttpResponseRedirect(reverse('App_login:profile_info'))
    return render(request,'App_login/background.html',context={'form':form})

App_login/templates/App_login/background.html
{% extends 'base.html' %}{% load crispy_forms_tags %}
{% block body_block %}
<div class="card shadow p-3 mb-5 bg-white rounded align-content-center center" style="width: 25rem;">
    
    {% if user.user_profile_bg %}
    <img style="height: 250px;" src="/media/{{user.user_profile_bg.profile_pic_bg}}" alt="">
    {% else %}
        <img src="/media/profile__bg_images/default.png" alt="">
    {% endif %}
        
<form action="" method="POST" enctype="multipart/form-data">
    {{form|crispy}}
    {% csrf_token %}
    <button class="btn btn-outline-primary" type="submit" name="Upload">Upload</button>
</form>
</div>
{% endblock body_block %}
    

App_login/templates/App_login/ch_pro_info.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body_block %}
<div class="container none sign m-4 p-4">
    <div class="row">
        <div class="col-md-6">
            <img src="{% static 'img/changeinfo.jpeg' %}" alt="">
        </div>
        <div class="col-md-6">
            <form method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <input type="submit" value="Update" class="btn btn-outline-primary"><br>
                <a href="{% url 'App_login:password_change' %}"> Change your password </a>
            </form>
        </div>
    </div>
</div>

{% endblock body_block %}

App_login/templates/App_login/login.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block body_block %}
<div class="sign ">
    <div class="row">
        <div class="col-md-6">
            <img src="{% static 'img/sign.jpg' %}" alt="">
        </div>
        <div class="col-md-6">
            <div class="forms">
                <h2>Sign Up </h2>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
                    <input type="submit" class="btn btn-outline-primary" value="Login ">
                </form>
                <br>
                <a href="{% url 'App_login:retistion' %}">
                    <p>Create a new accound @ Sign Up </p>
                </a>
            </div>
        </div>
    </div>

</div>
{% endblock body_block %}

App_login/templates/App_login/password_ch.html
{% extends 'base.html' %}{% load crispy_forms_tags %}
{% block body_block %}
<div class="card shadow p-3 mb-5 bg-white rounded align-content-center center" style="width: 25rem; height: 30rem;">
    <form action="" method="POST">
        {{form|crispy}}
        {% csrf_token %}
        <br>
        <button style="position: absolute; left: 50%; transform: translate(-50%,0%);" class="btn btn-outline-danger" type="submit" name="Change">Change</button>
    </form>
</div>
{% endblock body_block %}
    

App_login/templates/App_login/profile.html
{% extends 'base.html' %}{% load static %}
{% load custom_filters %}
{% block title_block %}
{{user.username}}
{% endblock title_block %}
{% block body_block %}

<div class="card_one">
    <div class="box">
        <div class="header">
            {% if user.user_profile_bg %}
            <img src="/media/{{user.user_profile_bg.profile_pic_bg}}" alt="">
            <a href="{% url 'App_login:change_pro_pic_bg' %}" type="button" class="btn btn-primary bg_img_up">
                Upload
            </a>
            {% else %}
            <img src="/media/profile__bg_images/default.png">
            <a href="{% url 'App_login:bag_img_profile' %}" type="button" class="btn btn-primary bg_img_up">
                Upload
            </a>
            {% endif %}
        </div>

        <div class="profile_pic_box">
            <div class="profile_pic">
                {% if user.user_profile %}
                <img src="/media/{{user.user_profile.profile_pic}}" alt="">
                <a href="{% url 'App_login:change_pro_pic' %}" type="button" class="btn btn-primary pr_img_up">
                    Upload
                </a>
                {% else %}
                <img src="/media/profile_images/default.png">
                <button type="button" class="btn btn-primary pr_img_up" data-bs-toggle="modal"
                    data-bs-target="#staticBackdrop">
                    Upload
                </button>
                {% endif %}
            </div>
        </div>
    </div>





    <!-- <img src="{%static 'img/changeinfo.jpeg' %}" alt=""> -->
    <h1>Username: {{user.username}}</h1>
    <h1>Name: {{user.first_name}} {{user.last_name}}</h1>
    <h1>Email : {{user.email}}</h1>



    <!-- my blog  -->
    <h2 class=" bg-danger p-3 " style="text-align:center; color: #ffffff;margin: 22px 0px;">My blog </h2>
    <div class="container p-4">
        {% for blog in user.blog_author.all  %}
        <br>
        
        <h2><span class="badge bg-primary">Title</span> : {{blog.blog_title}}</h2>
        <p>
            Publich date : <span class="time_date">{{blog.publich_date|date:"SHORT_DATE_FORMAT"}} - {{blog.publich_date|date:"h:i a"}}</span>
            <!-- Update -->
            / Update date
            :<span class="time_date">{{blog.update_date|date:"SHORT_DATE_FORMAT"}} - {{blog.update_date|date:"h:i a"}}</span>
        </p>

        <p>
            {% if blog.blog_comment.count == 0 %}
            Comment : <span class="time_date">{{blog.blog_comment.count}}</span>
            {% elif blog.blog_comment.count == 1 %}
            Comment : <span class="time_date">{{blog.blog_comment.count}}</span>
            {% else %}
            Comments : <span class="time_date">{{blog.blog_comment.count}}</span>
            {% endif %}
            <!-- likes -->
            / {% if blog.blog_like.count == 0 %}
            Like : <span class="time_date">{{blog.blog_like.count}}</span>
            {% elif blog.blog_like.count == 1 %}
            Like : <span class="time_date">{{blog.blog_like.count}}</span>
            {% else %}
            Likes : <span class="time_date">{{blog.blog_like.count}}</span>
            {% endif %}
            <!-- Author -->
            / Author : <span class="time_date"> @{{blog.author}}</span>
        </p>
        <div class="row">
            <div class="col-md-4">
                <img style="width: 100%; height: 13rem;" src="/media/{{blog.blog_img}}" alt="">
            </div>
            <div class="col-md-8">
                <p style="line-height: 1.8rem;">
                    {{blog.blog|range_filter|linebreaks}}
                    <a href="{% url 'App_post:blog_detiels' slug=blog.slug %}" style="text-decoration: none;">Read more
                        ......</a>
                    <!-- edit ///   -->
                    <a class="btn btn-danger" href="{% url 'App_post:EditBlog' pk=blog.pk %}"
                        style="text-decoration: none;">Edit Blog</a>
                </p>
            </div>
        </div>
        {% endfor %}
    </div>

</div>


<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <img src="{% static 'img/default.png' %}" alt="">
                <form action="" method="POST" enctype="multipart/form-data">
                    {{form}}
                    {% csrf_token %}
                    <input type="submit">
                </form>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- masseage load -->

{% endblock body_block %}

App_login/templates/App_login/profile_pic_ch.html
{% extends 'base.html' %}{% load crispy_forms_tags %}
{% block body_block %}
<div class="card shadow p-3 mb-5 bg-white rounded align-content-center center" style="width: 25rem;">
    
    {% if user.user_profile %}
    <img style="height:250px;" src="/media/{{user.user_profile.profile_pic}}" alt="">
        {% else %}
        <img src="/media/profile_images/default.png" alt="">
    {% endif %}
        
<form action="" method="POST" enctype="multipart/form-data">
    {{form|crispy}}
    {% csrf_token %}
    <button class="btn btn-outline-primary" type="submit" name="Upload">Upload</button>
</form>
</div>
{% endblock body_block %}
    

App_login/templates/App_login/registion.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block body_block %}
<div class="sign ">
    <div class="row">
        <div class="col-md-6">
            <img src="{% static 'img/sign.jpg' %}" alt="">
        </div>
        <div class="col-md-6">
            <div class="forms">
                <h2>Sign Up </h2>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
                    <input type="submit" class="btn btn-outline-primary" value="Sign Up">
                </form>
                <br>
                <a href="{% url 'App_login:login' %}">
                    <p>Already have a accound @login here </p>
                </a>
            </div>
        </div>
    </div>

</div>
{% endblock body_block %}