App_login/urls.py
from django.urls import path
from . import views

app_name = 'App_login'

urlpatterns = [
    path('retistion/',views.retistion, name='retistion'),
    path('login/',views.login_user, name='login'),
    # path('profile/',views.change_pro_pic, name='profile_info'),
    path('profile/',views.ProfilePicAdd, name='profile_info'),
    path('change_pro_pic/',views.change_pro_pic, name='change_pro_pic'),

    path('bag_img_profile/',views.bag_img_profile, name='bag_img_profile'),
    path('change_pro_pic_bg/',views.change_pro_pic_bg, name='change_pro_pic_bg'),
    
    path('password_change/',views.password_change, name='password_change'),

    path('logout/',views.logout_user, name='logout'),
    path('ChangeProInfo/',views.ChangeProInfo, name='ChangeProInfo'),
]

App_post/urls.py
from django.urls import path
from . import views

app_name= 'App_post'

urlpatterns = [
    path('', views.home, name='home'),
    path('MyBlogs', views.MyBlogs.as_view(), name='MyBlogs'),
    path('EditBlog/<pk>/', views.EditBlog.as_view(), name='EditBlog'),
    path('Create_blog/', views.Create_blog.as_view(), name='Create_blog'),
    # path(r'^BlogDitlis/(?P<slug>[\w-]+)/$',views.blog_deitels,name='blog_detiels'),
    path('BlogDitlis/<slug>/',views.blog_deitels,name='blog_detiels'),
    # path(r'^BlogDitlis1/(?P<slug>[\w-]+)/$',views.BlogDetitel,name='BlogDetitel1'),
    path('BlogDitlis1/<slug>/',views.BlogDetitel,name='BlogDetitel1'),
    path('Like/<pk>/',views.UserLike, name='like'),
    path('unLike/<pk>/',views.UserUnlike, name='Unlike'),
    path('orprofile/<username>/',views.OrderUserProfile, name='or_profile'),

]

New_Blog_Project_Mester/urls.py
from django.views.static import serve
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounds/', include('App_login.urls')),
    path('post/', include('App_post.urls')),
    path('',views.home, name='home'),
]

handler404 = views.handler404
handler400 = views.handler404

urlpatterns +=  staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_post/models.py
from typing import Tuple
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Blog(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_author')
    blog_title = models.CharField(verbose_name='Blog Title', max_length=264)
    blog = models.TextField(verbose_name='Put your mind',)
    blog_img = models.ImageField(upload_to='post_images',verbose_name='Blog Image')
    slug = models.SlugField(max_length=100,unique=True)
    publich_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    class Meta:
        ordering =['-publich_date',]

    def __str__(self):
        return self.blog_title

class comment(models.Model):
    blog = models.ForeignKey(Blog,on_delete=models.CASCADE,related_name='blog_comment')
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateField(auto_now_add=True)
    class Meta:
        ordering = ['-comment_date',]
    def __str__(self):
        return self.comment

class like(models.Model):
    blog = models.ForeignKey(Blog,on_delete=models.CASCADE,related_name='blog_like')
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_like')
    def __str__(self):
        return self.user

App_post/forms.py
from django.db import models
from django.db.models import fields
from .models import comment
from django import forms

class UserComment(forms.ModelForm):
    class Meta:
        model = comment
        fields = ('comment',)

App_post/views.py
from django.core.checks import messages
from django.shortcuts import render,HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView,ListView,DetailView,TemplateView,UpdateView
from .models import Blog,like
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import UserComment
from django.contrib.auth.models import User
import uuid
# Create your views here.

# def home(request):
#     return render(request,'App_post/home.html',context={})

class Create_blog (LoginRequiredMixin,CreateView):
    model = Blog
    template_name = "App_post/create_blog.html"
    fields = ('blog_title','blog','blog_img')
    def form_valid(self,form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = title.replace(" ", "-") + "-" + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('home'))


from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def home(request):
    user_list = Blog.objects.all()
    page = request.GET.get('page', 1)

    paginator = Paginator(user_list, 3)
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    return render(request, 'App_post/home.html', { 'blogs': users,'users':users })















# class home(ListView):
#     model = Blog
#     template_name = 'App_post/home.html'  # Default: <app_label>/<model_name>_list.html
#     context_object_name = 'blogs'  # Default: object_list
#     paginate_by = 4
#     queryset = Blog.objects.all()  # Default: Model.objects.all()




  
@login_required()
def blog_deitels(request, slug):
    blog = Blog.objects.get(slug=slug)
    Comment_user = UserComment()
    Agary_liked = like.objects.filter(blog=blog, user=request.user)
    if Agary_liked:
        liked = True
    else:
        liked = False

    if request.method == 'POST':
        Comment_user = UserComment(request.POST)
        if Comment_user.is_valid():
            comment = Comment_user.save(commit= False)
            comment.user = request.user
            comment.blog = blog
            comment.save()
            return HttpResponseRedirect(reverse('App_post:blog_detiels', kwargs={'slug':slug }))
    return render(request,'App_post/blog_detils.html',context={'blog':blog,'comment':Comment_user,'liked':liked,}) 


def BlogDetitel(request,slug):
    blog = Blog.objects.get(slug=slug)
    return render (request,'App_post/blog_detils_1.html',context={'blog':blog,})    

@login_required()
def UserLike(request,pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    Agaeary_liked = like.objects.filter(blog=blog,user=user)
    if not Agaeary_liked:
        like_post = like(blog=blog,user=user)
        like_post.save()
    return HttpResponseRedirect(reverse('App_post:blog_detiels',kwargs={'slug':blog.slug }))
    
@login_required()
def UserUnlike (request,pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    Ageary_liked = like.objects.filter(blog=blog, user=user)
    Ageary_liked.delete()
    return HttpResponseRedirect(reverse('App_post:blog_detiels',kwargs={'slug':blog.slug}))


class MyBlogs(LoginRequiredMixin,TemplateView):
    template_name = 'App_post/myblog.html'

class EditBlog(LoginRequiredMixin,UpdateView):
    model = Blog
    fields = ('blog_title','blog','blog_img')
    template_name = 'App_post/edit.html'

    def get_success_url(self):
        # messages.success(request,'You have successfully Login')
        return reverse_lazy('App_post:MyBlogs',)



def OrderUserProfile(request, username):
    order_user = User.objects.get(username=username)
    return render(request,'App_post/or_profile.html',context={'profile':order_user})

App_post/templates/App_post/blog_detils.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
<div class="container">
    <h2><span class="badge bg-primary">Title</span> : {{blog.blog_title}}</h2>
    <p>
        Publich date : <span class="time_date">{{blog.publich_date|date:"SHORT_DATE_FORMAT"}} -
            {{blog.publich_date|date:"h:i a"}}</span>
        <!-- Update -->
        / Update date
        :<span class="time_date">{{blog.update_date|date:"SHORT_DATE_FORMAT"}} -
            {{blog.update_date|date:"h:i a"}}</span>
    </p>

    <p>
        {% if blog.blog_comment.count == 0 %}
        Comment : <span class="time_date">{{blog.blog_comment.count}}</span>
        {% elif blog.blog_comment.count == 1 %}
        Comment : <span class="time_date">{{blog.blog_comment.count}}</span>
        {% else %}
        Comments : <span class="time_date">{{blog.blog_comment.count}}</span>
        {% endif %}
        <!-- likes -->
        / {% if blog.blog_like.count == 0 %}
        Like : <span class="time_date">{{blog.blog_like.count}}</span>
        {% elif blog.blog_like.count == 1 %}
        Like : <span class="time_date">{{blog.blog_like.count}}</span>
        {% else %}
        Likes : <span class="time_date">{{blog.blog_like.count}}</span>
        {% endif %}
        <!-- Author -->
        / Author : <a href="{% url 'App_post:or_profile' username=blog.author %}" class="time_date"> @{{blog.author}}</a>
    </p>



    <img src="/media/{{blog.blog_img}}" alt="" style="height: 500px;width:100%;">
    <p>{{blog.blog|linebreaks}}</p><br>
    <hr>


    <!-- Likes \\\\\\\\\\\\ -->
    <h3>
        {% if blog.blog_like.count == 0 %}
        Like : <span class="time_date">{{blog.blog_like.count}}</span>
        {% elif blog.blog_like.count == 1 %}
        Like : <span class="time_date">{{blog.blog_like.count}}</span>
        {% else %}
        Likes : <span class="time_date">{{blog.blog_like.count}}</span>
        {% endif %}
    </h3>
    {% if not liked %}
    <a style="font-size: 7rem;" href="{% url 'App_post:like' pk=blog.pk %}"><i class="fas fa-thumbs-up"></i></a>
    {% else %}
    <a style="font-size: 7rem;" href="{% url 'App_post:Unlike' pk=blog.pk %}"><i class="fas fa-thumbs-down"></i></a>
    {% endif %}

    <div class="row">
        <div class="col-md-4">
            <!-- comments show\\\\\\\ -->
            <h3>
                {% if blog.blog_comment.count == 0 %}
                Comment : <span class="time_date">{{blog.blog_comment.count}}</span>
                {% elif blog.blog_comment.count == 1 %}
                Comment : <span class="time_date">{{blog.blog_comment.count}}</span>
                {% else %}
                Comments : <span class="time_date">{{blog.blog_comment.count}}</span>
                {% endif %}
            </h3>
            <!-- comment\\\\\\\\\\\\ -->
            {% for comment in blog.blog_comment.all %}
            <ul>
                <li><span class="time_date">@{{comment.user}}</span><br> {{comment.comment}}</li>
            </ul>
            {% endfor %}
            <!-- ///////////////// -->
        </div>
        <div class="col-md-8">
            <form action="" method="POST">
                {{comment|crispy}}{% csrf_token %}<br>
                <button class="btn btn-outline-primary">Comment</button><br><br>
            </form>
        </div>
    </div>
</div>



{% endblock body_block %}

App_post/templates/App_post/blog_detils_1.html
{% extends 'base.html' %}{% load crispy_forms_tags %}
{% block body_block %}
<div class="container">
    <h2><span class="badge bg-primary">Title</span>{{blog.blog_title}}</h2>
 <p>
        Publich date : <span class="time_date">{{blog.publich_date|date:"SHORT_DATE_FORMAT"}} -
            {{blog.publich_date|date:"h:i a"}}</span>
        <!-- Update -->
        / Update date
        :<span class="time_date">{{blog.update_date|date:"SHORT_DATE_FORMAT"}} -
            {{blog.update_date|date:"h:i a"}}</span>
    </p>

    <p>
        {% if blog.blog_comment.count == 0 %}
        Comment : <span class="time_date">{{blog.blog_comment.count}}</span>
        {% elif blog.blog_comment.count == 1 %}
        Comment : <span class="time_date">{{blog.blog_comment.count}}</span>
        {% else %}
        Comments : <span class="time_date">{{blog.blog_comment.count}}</span>
        {% endif %}
        <!-- likes -->
        / {% if blog.blog_like.count == 0 %}
        Like : <span class="time_date">{{blog.blog_like.count}}</span>
        {% elif blog.blog_like.count == 1 %}
        Like : <span class="time_date">{{blog.blog_like.count}}</span>
        {% else %}
        Likes : <span class="time_date">{{blog.blog_like.count}}</span>
        {% endif %}
        <!-- Author -->
        / Author : <a href="{% url 'App_post:or_profile' username=blog.author %}" class="time_date"> @{{blog.author}}</a>
    </p>
    <img src="/media/{{blog.blog_img}}" alt="" style="height: 500px;width:100%;">
    <p>{{blog.blog|linebreaks}}</p>
    <br>
    <hr>

 <a style="font-size: 7rem;" target="blank" href="{% url 'App_login:login' %}"><i class="fas fa-thumbs-up"></i></a>
    <a href="{% url 'App_login:login' %}" class="btn btn-outline-primary m-4">Comment</a>
   
</div>


{% endblock body_block %}

App_post/templates/App_post/create_blog.html
{% extends "base.html" %}{% load crispy_forms_tags %}{% block body_block %}
<div class="card p-4 m-4">
<h3 style="text-align: center;">Create a blog post </h3><hr>
  <form action="" method="POST" enctype="multipart/form-data">
      {{form|crispy}}
      {% csrf_token %}
      <br>
      <button style="position: absolute; left: 50%; transform: translate(-50%,0%);" class="btn btn-outline-primary ">Create</button>
      <br>
  </form>
</div>
{% endblock body_block %}

App_post/templates/App_post/edit.html
{% extends 'base.html' %}{% load crispy_forms_tags %}
{% block body_block %}
<div class="container">
    <h2 class=" bg-danger p-3" style="text-align:center; color: #fff;">My Blog Edit </h2>
    {% if blog.author == user %}
    <form action="" enctype="multipart/form-data" method="POST">
        {{form|crispy}}
        {% csrf_token %}
        <button class="btn btn-danger m-lg-4" type="submit">Update</button>
    </form>
    {% else %}
    <p>Your are not allowed to view this page. 404</p>
    {% endif %}
</div>

{% endblock body_block %}

App_post/templates/App_post/home.html
{% extends "base.html" %}{% load custom_filters %}{% block body_block %}


<div class="container">
    {% for blog in blogs  %}
    <br>
    <h2><span class="badge bg-primary">Title</span> :
        {% if user.is_authenticated %}
        <a style="color:#212529; text-decoration:none;" href="{% url 'App_post:blog_detiels' slug=blog.slug %}"
            style="text-decoration: none;">{{blog.blog_title|range_filter_filter}}</a>
        {% else %}
        <a style="color:#212529; text-decoration:none;" href="{% url 'App_post:BlogDetitel1' slug=blog.slug %}"
            style="text-decoration: none;">{{blog.blog_title}}</a>
        {% endif %}
    </h2>
    <p>
        Publich date : <span class="time_date">{{blog.publich_date|date:"SHORT_DATE_FORMAT"}} -
            {{blog.publich_date|date:"h:i a"}}</span>
        <!-- Update -->
        / Update date
        :<span class="time_date">{{blog.update_date|date:"SHORT_DATE_FORMAT"}} -
            {{blog.update_date|date:"h:i a"}}</span>
    </p>

    <p>
        {% if blog.blog_comment.count == 0 %}
        Comment : <span class="time_date">{{blog.blog_comment.count}}</span>
        {% elif blog.blog_comment.count == 1 %}
        Comment : <span class="time_date">{{blog.blog_comment.count}}</span>
        {% else %}
        Comments : <span class="time_date">{{blog.blog_comment.count}}</span>
        {% endif %}
        <!-- likes -->
        / {% if blog.blog_like.count == 0 %}
        Like : <span class="time_date">{{blog.blog_like.count}}</span>
        {% elif blog.blog_like.count == 1 %}
        Like : <span class="time_date">{{blog.blog_like.count}}</span>
        {% else %}
        Likes : <span class="time_date">{{blog.blog_like.count}}</span>
        {% endif %}
        <!-- Author -->
        / Author : <a href="{% url 'App_post:or_profile' username=blog.author %}" class="time_date">
            @{{blog.author}}</a>
    </p>


    <div class="row">
        <div class="col-md-4">
            <img style="width: 100%; height: 13rem;" src="/media/{{blog.blog_img}}" alt="">
        </div>
        <div class="col-md-8">
            <p style="line-height: 1.8rem;">
                {{blog.blog|range_filter|linebreaks}}

                {% if user.is_authenticated %}
                <a href="{% url 'App_post:blog_detiels' slug=blog.slug %}" style="text-decoration: none;">Read more
                    ......</a>
                {% else %}
                <a href="{% url 'App_post:BlogDetitel1' slug=blog.slug %}" style="text-decoration: none;">Read more
                    ......</a>
                {% endif %}
            </p>
        </div>
    </div>
    {% endfor %}
</div>



<!-- ////////////////pagination bootstrap function base ///////////////////// -->

{% if users.has_other_pages %}
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if users.has_previous %}
    <li class="page-item ">
        <a class="page-link" href="?page={{ users.previous_page_number }}">Previeos</a></li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previeos</a>
    </li>
    {% endif %}
    {% for i in users.paginator.page_range %}
      {% if users.number == i %}
        <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
      <li class="page-item ">
        <a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if users.has_next %}
    <li class="page-item ">
        <a class="page-link" href="?page={{ users.next_page_number }}">Next</a></li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

<!-- ////////////////pagination bootstrap class base ///////////////////// -->
  <!-- <div class="container"> 
    {% if is_paginated %}
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
            {% endif %}
            {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
            <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span>
            </li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div> -->
<!-- End pagination bootstrap  -->

{% endblock body_block %}

App_post/templates/App_post/myblog.html
{% extends "base.html" %}{% load custom_filters %}{% block body_block %}
<div class="container p-4">
    <h2 class=" bg-info p-3 "  style="text-align: center;">My blog </h2>
    {% for blog in user.blog_author.all  %}
    <br>
    <h2><span class="badge bg-primary">Title</span> : {{blog.blog_title}}</h2>
    <p>
        Publich date : <span class="time_date">{{blog.publich_date|date:"SHORT_DATE_FORMAT"}} -
            {{blog.publich_date|date:"h:i a"}}</span>
        <!-- Update -->
        / Update date
        :<span class="time_date">{{blog.update_date|date:"SHORT_DATE_FORMAT"}} -
            {{blog.update_date|date:"h:i a"}}</span>
    </p>

    <p>
        {% if blog.blog_comment.count == 0 %}
        Comment : <span class="time_date">{{blog.blog_comment.count}}</span>
        {% elif blog.blog_comment.count == 1 %}
        Comment : <span class="time_date">{{blog.blog_comment.count}}</span>
        {% else %}
        Comments : <span class="time_date">{{blog.blog_comment.count}}</span>
        {% endif %}
        <!-- likes -->
        / {% if blog.blog_like.count == 0 %}
        Like : <span class="time_date">{{blog.blog_like.count}}</span>
        {% elif blog.blog_like.count == 1 %}
        Like : <span class="time_date">{{blog.blog_like.count}}</span>
        {% else %}
        Likes : <span class="time_date">{{blog.blog_like.count}}</span>
        {% endif %}
        <!-- Author -->
        / Author : <span class="time_date"> @{{blog.author}}</span>
    </p>
    <div class="row">
        <div class="col-md-4">
            <img style="width: 100%; height: 13rem;" src="/media/{{blog.blog_img}}" alt="">
        </div>
        <div class="col-md-8">
            <p style="line-height: 1.8rem;">
                {{blog.blog|range_filter|linebreaks}}
                <a href="{% url 'App_post:blog_detiels' slug=blog.slug %}" style="text-decoration: none;">Read more ......</a>
                <!-- edit ///   -->
                <a class="btn btn-danger" href="{% url 'App_post:EditBlog' pk=blog.pk %}" style="text-decoration: none;">Edit Blog</a>
            </p>
        </div>
    </div>
    {% endfor %}
</div>


{% endblock body_block %}

App_post/templates/App_post/or_profile.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% block body_block %}

<div class="card_one">
    <div class="box">
        <div class="header">
            {% if profile.user_profile_bg %}
            <img src="/media/{{profile.user_profile_bg.profile_pic_bg}}" alt="">
            {% else %}
            <img src="/media/profile__bg_images/default.png">
            {% endif %}
        </div>

        <div class="profile_pic_box">
            <div class="profile_pic">
                {% if profile.user_profile %}
                <img src="/media/{{profile.user_profile.profile_pic}}" alt="">
                {% else %}
                <img src="/media/profile_images/default.png">
                {% endif %}
            </div>
        </div>
    </div>

    <!-- <img src="{%static 'img/changeinfo.jpeg' %}" alt=""> -->
    <h1>Username: {{profile.username}}</h1>
    <h1>Name: {{profile.first_name}} {{profile.last_name}}</h1>
    <h1>Email : {{profile.email}}</h1>



    <!-- my blog  -->
    <h2 class=" bg-danger p-3 " style="text-align:center; color: #ffffff;margin: 22px 0px;">{{profile.username}}  blog </h2>
    <div class="container p-4">
        {% for blog in profile.blog_author.all  %}
        <br>
        
        <h2><span class="badge bg-primary">Title</span> :
            {% if user.is_authenticated %}
            <a style="color:#212529; text-decoration:none;" href="{% url 'App_post:blog_detiels' slug=blog.slug %}" style="text-decoration: none;">{{blog.blog_title}}</a>
            {% else %}
            <a style="color:#212529; text-decoration:none;" href="{% url 'App_post:BlogDetitel1' slug=blog.slug %}" style="text-decoration: none;">{{blog.blog_title}}</a>
            {% endif %}
        </h2>
        <p>
            Publich date : <span class="time_date">{{blog.publich_date|date:"SHORT_DATE_FORMAT"}} - {{blog.publich_date|date:"h:i a"}}</span>
            <!-- Update -->
            / Update date
            :<span class="time_date">{{blog.update_date|date:"SHORT_DATE_FORMAT"}} - {{blog.update_date|date:"h:i a"}}</span>
        </p>

        <p>
            {% if blog.blog_comment.count == 0 %}
            Comment : <span class="time_date">{{blog.blog_comment.count}}</span>
            {% elif blog.blog_comment.count == 1 %}
            Comment : <span class="time_date">{{blog.blog_comment.count}}</span>
            {% else %}
            Comments : <span class="time_date">{{blog.blog_comment.count}}</span>
            {% endif %}
            <!-- likes -->
            / {% if blog.blog_like.count == 0 %}
            Like : <span class="time_date">{{blog.blog_like.count}}</span>
            {% elif blog.blog_like.count == 1 %}
            Like : <span class="time_date">{{blog.blog_like.count}}</span>
            {% else %}
            Likes : <span class="time_date">{{blog.blog_like.count}}</span>
            {% endif %}
            <!-- Author -->
            / Author : <span class="time_date"> @{{blog.author}}</span>
        </p>
        <div class="row">
            <div class="col-md-4">
                <img style="width: 100%; height: 13rem;" src="/media/{{blog.blog_img}}" alt="">
            </div>
            <div class="col-md-8">
                <p style="line-height: 1.8rem;">
                    {{blog.blog|range_filter|linebreaks}}
                    {% if user.is_authenticated %}
                    <a href="{% url 'App_post:blog_detiels' slug=blog.slug %}" style="text-decoration: none;">Read more
                        ......</a>
                    {% else %}
                    <a href="{% url 'App_post:BlogDetitel1' slug=blog.slug %}" style="text-decoration: none;">Read more
                        ......</a>
                    {% endif %}
                </p>
            </div>
        </div>
        {% endfor %}
    </div>

</div>


{% endblock body_block %}